// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqq_yluji1mhamypF4wxMWlwqjhz6or1E',
    appId: '1:617270951701:android:bc361a952ad3e9ec29b31c',
    messagingSenderId: '617270951701',
    projectId: 'tourism-app-7e3df',
    storageBucket: 'tourism-app-7e3df.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiHDefwZI9SXxj6ONaRAPuzeWh0SJLbH0',
    appId: '1:617270951701:web:4d4be57afa8d57f429b31c',
    messagingSenderId: '617270951701',
    projectId: 'tourism-app-7e3df',
    authDomain: 'tourism-app-7e3df.firebaseapp.com',
    storageBucket: 'tourism-app-7e3df.firebasestorage.app',
    measurementId: 'G-K3H11WHT58',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe8INNcp1073S4lFjMEBUckgtmmV_TnyE',
    appId: '1:617270951701:ios:4ace1835498e122f29b31c',
    messagingSenderId: '617270951701',
    projectId: 'tourism-app-7e3df',
    storageBucket: 'tourism-app-7e3df.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe8INNcp1073S4lFjMEBUckgtmmV_TnyE',
    appId: '1:617270951701:ios:4ace1835498e122f29b31c',
    messagingSenderId: '617270951701',
    projectId: 'tourism-app-7e3df',
    storageBucket: 'tourism-app-7e3df.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiHDefwZI9SXxj6ONaRAPuzeWh0SJLbH0',
    appId: '1:617270951701:web:be09dfde9d408d8029b31c',
    messagingSenderId: '617270951701',
    projectId: 'tourism-app-7e3df',
    authDomain: 'tourism-app-7e3df.firebaseapp.com',
    storageBucket: 'tourism-app-7e3df.firebasestorage.app',
    measurementId: 'G-NSSQLX9TPJ',
  );

}